In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

In [2]:
def init_weights(shape):
    return tf.Variable(tf.random_normal(shape, stddev=0.01))

def model(X, w_h, w_o):
    h = tf.nn.sigmoid(tf.matmul(X, w_h)) # this is a basic mlp, think 2 stacked logistic regressions
    return tf.matmul(h, w_o) # note that we dont take the softmax at the end because our cost fn does that for us

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
trX, trY, teX, teY = mnist.train.images, mnist.train.labels, mnist.test.images, mnist.test.labels

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
X = tf.placeholder("float", [None, 784])
Y = tf.placeholder("float", [None, 10])

w_h = init_weights([784, 625]) # create symbolic variables
w_o = init_weights([625, 10])

py_x = model(X, w_h, w_o)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=py_x, labels=Y)) # compute costs
train_op = tf.train.GradientDescentOptimizer(0.05).minimize(cost) # construct an optimizer
predict_op = tf.argmax(py_x, 1)

In [4]:
# Launch the graph in a session
with tf.Session() as sess:
    # you need to initialize all variables
    tf.global_variables_initializer().run()

    for i in range(100):
        for start, end in zip(range(0, len(trX), 128), range(128, len(trX)+1, 128)):
            sess.run(train_op, feed_dict={X: trX[start:end], Y: trY[start:end]})
        print(i, np.mean(np.argmax(teY, axis=1) ==
                         sess.run(predict_op, feed_dict={X: teX})))

0 0.6837
1 0.8222
2 0.861
3 0.8801
4 0.8881
5 0.8937
6 0.897
7 0.9005
8 0.9034
9 0.905
10 0.9078
11 0.91
12 0.912
13 0.9127
14 0.9142
15 0.9151
16 0.9153
17 0.9161
18 0.917
19 0.918
20 0.9183
21 0.9189
22 0.9193
23 0.9195
24 0.92
25 0.9202
26 0.9203
27 0.9208
28 0.9216
29 0.9222
30 0.9228
31 0.923
32 0.9233
33 0.9235
34 0.924
35 0.925
36 0.9256
37 0.9259
38 0.9261
39 0.9265
40 0.927
41 0.9273
42 0.928
43 0.9286
44 0.9293
45 0.93
46 0.9308
47 0.9315
48 0.9319
49 0.9327
50 0.9334
51 0.9336
52 0.9341
53 0.9341
54 0.9349
55 0.9357
56 0.9365
57 0.937
58 0.938
59 0.9383
60 0.9387
61 0.9391
62 0.9394
63 0.94
64 0.9407
65 0.9415
66 0.9418
67 0.9423
68 0.943
69 0.9437
70 0.9441
71 0.944
72 0.9444
73 0.945
74 0.9455
75 0.9459
76 0.9465
77 0.9468
78 0.9473
79 0.9478
80 0.9483
81 0.9486
82 0.9491
83 0.9497
84 0.9503
85 0.9509
86 0.9513
87 0.9519
88 0.9523
89 0.9524
90 0.9526
91 0.9525
92 0.9531
93 0.9534
94 0.9536
95 0.9539
96 0.9541
97 0.9543
98 0.9545
99 0.9548


### below is my code

In [5]:
a = tf.Variable([[1, 2], [3, 4]])

In [7]:
b = tf.Variable([[2, 3], [4, 5]])

In [8]:
out = tf.matmul(a, b)

In [10]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print (sess.run(out))

[[10 13]
 [22 29]]


In [11]:
c = np.array([[1, 2], [3, 4]])

In [12]:
d = np.array([[2, 3], [4, 5]])

In [13]:
c.dot(d)

array([[10, 13],
       [22, 29]])

In [14]:
np.multiply(c, d)

array([[ 2,  6],
       [12, 20]])

In [15]:
c

array([[1, 2],
       [3, 4]])

In [16]:
d

array([[2, 3],
       [4, 5]])

In [18]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

In [19]:
def init_weight(shape):
    return tf.Variable(tf.random_normal(shape, stddev=1.0))

In [20]:
def model(X, w_h, w_o):
    h = tf.nn.sigmoid(tf.matmul(X, w_h))
    return tf.matmul(h, w_o)

In [24]:
X = tf.placeholder('float', [None, 784])
Y = tf.placeholder('float', [None, 10])

In [25]:
w_h = init_weight([784, 625])
w_o = init_weight([625, 10])

In [26]:
py_x = model(X, w_h, w_o)

In [27]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=py_x, labels=Y))

In [28]:
train_op = tf.train.GradientDescentOptimizer(0.05).minimize(cost)

In [29]:
predict_op = tf.argmax(py_x, 1)

In [30]:
help(tf.arg_max)

Help on function arg_max in module tensorflow.python.ops.gen_math_ops:

arg_max(input, dimension, name=None)
    Returns the index with the largest value across dimensions of a tensor.
    
    Note that in case of ties the identity of the return value is not guaranteed.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int64`, `int32`, `uint8`, `uint16`, `int16`, `int8`, `complex64`, `complex128`, `qint8`, `quint8`, `qint32`, `half`.
      dimension: A `Tensor`. Must be one of the following types: `int32`, `int64`.
        int32, 0 <= dimension < rank(input).  Describes which dimension
        of the input Tensor to reduce across. For vectors, use dimension = 0.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `int64`.



In [32]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    for i in range(100):
        for start, end in zip(range(0, len(trX), 128), range(128, len(trX)+1, 128)):
            sess.run(train_op, feed_dict={X: trX[start: end], Y:trY[start: end]})
        print (i, np.mean(np.argmax(teY, axis=1) == sess.run(predict_op, feed_dict={X: teX})))

0 0.7278
1 0.8012
2 0.8286
3 0.8445
4 0.8554
5 0.8641
6 0.8706
7 0.8751
8 0.8795
9 0.8829
10 0.8853
11 0.8878
12 0.8905
13 0.8931
14 0.895
15 0.8961
16 0.8971
17 0.8986
18 0.8996
19 0.9013
20 0.9021
21 0.903
22 0.904
23 0.9051
24 0.9062
25 0.9072
26 0.9084
27 0.9093
28 0.9104
29 0.9112
30 0.9119
31 0.9125
32 0.913
33 0.9138
34 0.9142
35 0.9147
36 0.9153
37 0.9156
38 0.9164
39 0.9169
40 0.9171
41 0.9177
42 0.918
43 0.9185
44 0.919
45 0.9193
46 0.9197
47 0.9198
48 0.9201
49 0.9201
50 0.9204
51 0.9202
52 0.92
53 0.9202
54 0.9205
55 0.9208
56 0.9212
57 0.922
58 0.9222
59 0.9221
60 0.9222
61 0.9223
62 0.9228
63 0.923
64 0.9236
65 0.9236
66 0.9237
67 0.9239
68 0.9241
69 0.9243
70 0.9242
71 0.9244
72 0.9246
73 0.9249
74 0.9248
75 0.9249
76 0.9252
77 0.9256
78 0.9258
79 0.9258
80 0.9259
81 0.9262
82 0.9263
83 0.9265
84 0.927
85 0.9276
86 0.9281
87 0.9285
88 0.9286
89 0.9286
90 0.9289
91 0.9292
92 0.9296
93 0.9301
94 0.9306
95 0.9308
96 0.931
97 0.9309
98 0.9309
99 0.9312
